name: 🚀 Deploy Angular App to EC2

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗️ Build Angular Project
        run: npm run build -- --configuration production

      - name: 🔐 Setup SSH Key
        run: |
          echo "$EC2_SSH_KEY" | tr -d '\r' > ssh_key
          chmod 600 ssh_key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: 📂 Create Folders and Backup Old Build
        run: |
          echo "🟢 Connecting to EC2 to prepare directories..."
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
            mkdir -p /home/ec2-user/datakavachfrontend/datakawach/dist && \
            if [ -d /home/ec2-user/datakavachfrontend/datakawach/dist/hrkui ]; then \
              mkdir -p /home/ec2-user/datakavachfrontend/datakawach/backup && \
              mv /home/ec2-user/datakavachfrontend/datakawach/dist/hrkui /home/ec2-user/datakavachfrontend/datakawach/backup/hrkui-$(date +%s); \
            fi"

      - name: 📤 Deploy New Build to EC2
        run: |
          echo "🚀 Uploading new build files..."
          scp -i ssh_key -o StrictHostKeyChecking=no -r dist/hrkui/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/datakavachfrontend/datakawach/dist/hrkui

      - name: ✅ Done
        run: echo "🎉 Deployment Successful!"
